print("=" * 50)
print("AI ESSAY WRITING ASSISTANT")
print("=" * 50)
topic = input("Enter the essay topic: ")
essay_type = input("Enter essay type (Informative/Persuasive/Narrative): ")
length = input("Enter length (Short/Medium/Long): ")
print("\nGenerating Essay...")
print("=" * 50)
print("\nTITLE:", topic.upper())
print("\nINTRODUCTION")
print(topic, "is an interesting topic to learn about.")
print("People often talk about", topic, "because it is important.")
print("This essay will explain some useful information about it.")
print("\nBODY PARAGRAPH 1")
print(topic, "plays an important role in our daily lives.")
print("It helps people in many different ways.")
print("Learning about", topic, "can increase our knowledge.")
print("\nBODY PARAGRAPH 2")
print("There are many facts related to", topic + ".")
print("Students can learn valuable lessons from it.")
print("It can also help us understand the world around us.")
if length.lower() == "long":
    print("\nBODY PARAGRAPH 3")
    print(topic, "has a positive impact on society.")
    print("Many experts study and research this topic.")
    print("Its importance continues to grow every year.")

    print("\nBODY PARAGRAPH 4")
    print("Understanding", topic, "helps us make better decisions.")
    print("It encourages learning and personal growth.")
    print("Everyone can benefit from knowing more about")
    print("\nCONCLUTION")
    print("In conclution", topic, "is a variable topic.")
    print("It teaches us important ideas and lessons.")
    print("We should continue exploring and learning more about it.")
    print("\nESSAY DETAILS")
    print("Topic:", topic)
    print("Essay Type:", essay_type)
    print("Essay Length:", length)
    print("Thank You for using the AI Essay Writing Assistant!")
    print("=" * 50)